### ISSUE TITLE
xunit tests fail for the repo in the details below

### ISSUE THREAD

**Issue by 7sharp9** [LambdaFactory/Neptune-public#10]
Repo is: https://github.com/pedromsantos/vaughan

Error even in diagnostic mode was vague:

```
notificationsAlerts.ts:39 Running test failed - Build failed
  | e.onDidNotificationChange | @ | notificationsAlerts.ts:39
```

**Comment by 7sharp9** [comment]
Tests appear in the test explorer but the error above happens on run or debug.

**Comment by Krzysztof-Cieslak** [comment]
Check `msbuild` output channel (`View: Toggle Output` and choose `msbuild` from the list)

**Comment by 7sharp9** [comment]
Hmm, curious:
```
/usr/local/share/dotnet/sdk/2.1.4/FSharp/Microsoft.FSharp.Targets(263,9): error MSB6003: The specified task executable "fsc.exe" could not be run. Permission denied
```

**Comment by Krzysztof-Cieslak** [comment]
Uhh.... 1st time I see such error

**Comment by Krzysztof-Cieslak** [comment]
This seems to work just fine on my Linux machine:

![screenshot from 2018-04-01 20 30 53](https://user-images.githubusercontent.com/5427083/38176232-a1688bd2-35eb-11e8-95d9-1a374cd3158c.png)

**Comment by 7sharp9** [comment]
Hmm, Im not quite sure whats going wrong, it maybe a problem with my machine /shrug
