### ISSUE TITLE
Test Explorer not visible

### ISSUE THREAD

**Issue by samhanes** [LambdaFactory/Neptune-public#17]
Neptune 1.2.0
VS Code 1.22.2 Windows

Just did a fresh install of Neptune; I don't see the Test Explorer and I get the error "No view is registered with id: neptune.testExplorer"

**Comment by samhanes** [comment]
This appears to have been introduced with Neptune 1.2.0 - I downgraded to 1.1.3 and the Test Explorer is visible as expected.

**Comment by Krzysztof-Cieslak** [comment]
Please, update VSCode to latest version (1.23.0). Test explorer now has its own icon in Activity Bar.

![imageedit_2_4087569620](https://user-images.githubusercontent.com/5427083/39667430-6174636c-50b6-11e8-806a-ecc22cfd4686.png)

**Comment by samhanes** [comment]
That did it, thanks!
