### ISSUE TITLE
Cannot enter license

### ISSUE THREAD

**Issue by priort** [LambdaFactory/Neptune-public#19]
I have a Neptune license and I had it installed on my personal laptop on macOS. I also want to use it on my work machine from inside windows on Parallels. 
However, I can't seem to be able to enter the license anywhere. I just get a notification to say my subscription has expired (I presume that means the trial period).
I have uninstalled Neptune in vscode on my personal machine to see if that makes a difference but it doesn't seem to.

Is it possible to use my one Neptune subscription in my different instances of vscode? I actually have 4 instances of vscode - 2 on personal macbook (macOS and win parallels) and 2 on my work macbook.

<img width="496" alt="screen shot 2018-06-26 at 13 44 28" src="https://user-images.githubusercontent.com/13556648/41912436-ae6aa172-7947-11e8-8d4b-5c8fdc380daa.png">

**Comment by Krzysztof-Cieslak** [comment]
> Is it possible to use my one Neptune subscription in my different instances of vscode?

Yes, this is fine. 

---
I've just released 1.3.1 which should ask for license in all cases.

**Comment by priort** [comment]
Nice one, thanks a million!
