### ISSUE TITLE
Group tests by project

### ISSUE THREAD

**Issue by JonCanning** [LambdaFactory/Neptune-public#4]
I've got a number of test projects in my solution; could the tests be grouped by project?

**Comment by Krzysztof-Cieslak** [comment]
In `1.1.0` I've added new display mode that groups tests by projects and files

**Comment by JonCanning** [comment]
Something's wrong :(

![screen shot 2018-04-11 at 14 36 21](https://user-images.githubusercontent.com/671232/38620196-d265911a-3d95-11e8-9b7a-9d6dcfc5d75a.png)

**Comment by ovatsus** [comment]
I'm getting the same after clicking the toggle mode button

**Comment by Krzysztof-Cieslak** [comment]
Fixed released, `1.1.1` should be available in a few minutes.

**Comment by ovatsus** [comment]
Works fine now
