### ISSUE TITLE
[xUnit] Theory tests appear in Test Explorer twice

### ISSUE THREAD

**Issue by sasmithjr** [LambdaFactory/Neptune-public#5]
In the Test Explorer, xUnit tests with the TheoryAttribute appear twice.

If the test fails, it reports as failed correctly in both places. The times match up, too. Fixing the test and running it correctly updates in both places, as well.

Probably related: the `| Run Test | Debug Test` shows up twice for the Theory tests but not Fact tests. If it's not related, let me know and I'll open a separate issue and edit this one to reflect.

Repro repo: [here](https://github.com/sasmithjr/Neptune-xUnit-Theory-Repro/tree/4dc849c335336e9547cbdf63b6053dca60abaae7)

macOS: 10.13.3
VSCode: 1.21.1
Ionide: 3.18.1
C#: 1.14.0
`dotnet --version`: v2.1.101
xUnit & xUnit.runner.visualstudio: v2.3.1

![screen shot 2018-03-29 at 10 03 01 am](https://user-images.githubusercontent.com/8585995/38093279-73744f1e-3338-11e8-9703-a0e8ca57a7ad.png)

![screen shot 2018-03-29 at 10 07 05 am](https://user-images.githubusercontent.com/8585995/38093440-f9322f68-3338-11e8-911b-c26b503917e9.png)

**Comment by Krzysztof-Cieslak** [comment]
Should be fixed in `1.0.6`

**Comment by sasmithjr** [comment]
Looks good. Thanks!
