### ISSUE TITLE
Extraneous gutter icon with certain Expecto helpers

### ISSUE THREAD

**Issue by pblasucci** [LambdaFactory/Neptune-public#7]
Test cases which contain certain "test helpers" (e.g. `skipTest`, `failTest`) display an extra gutter icon

_Note: this might not be a bug, per se... but it's a bit confusing when "scanning" a file_

+ Work-around: none
+ Platform:  Windows 10
+ Runtime: .NET Core 2.1

Minimal reproduction: https://github.com/pblasucci/neptune_expecto_repro

**Comment by Krzysztof-Cieslak** [comment]
Should be fixed in `1.0.8`

**Comment by pblasucci** [comment]
👍 Works great! Thanks!
