### ISSUE TITLE
Expecto "TestBuilder" tests are not detected.

### ISSUE THREAD

**Issue by pblasucci** [LambdaFactory/Neptune-public#8]
Tests constructed using the test "name" {} computation expression syntax are NOT detected (i.e. no icons, don;t show up in test explorer, no code lens)

+ Work-around: none
+ Platform: Windows 10
+ Runtime: .NET Core 2.1

Minimal reproduction: https://github.com/pblasucci/neptune_expecto_repro

**Comment by Krzysztof-Cieslak** [comment]
Should be fixed in `1.0.8`

**Comment by pblasucci** [comment]
👍 Looks great! Thanks!
