### ISSUE TITLE
FsCheck.Xunit tests don't appear in test explorer but run with dotnet test

### ISSUE THREAD

**Issue by bentayloruk** [LambdaFactory/Neptune-public#9]
I can't get Neptune to see FsCheck Xunit tests.  I have a project containing numerous properties, but they do not appear in the Neptune Test Explorer panel.  I can run them fine, with `dotnet test`.

I've hacked my solution down to a small repro (attached).  The two properties in this repro will run with `dotnet test` but do not appear with Neptune.

Let me know if you need more info.

[FsCheckRepro.Properties.zip](https://github.com/LambdaFactory/Neptune-public/files/1865649/FsCheckRepro.Properties.zip)

**Comment by Krzysztof-Cieslak** [comment]
Should be fixed in `1.0.7`

**Comment by bentayloruk** [comment]
Thanks.  Works for me!
